word_list = [
    # 1–20
    "Genshin Impact",
    "Call of Duty: Mobile",
    "Honkai: Star Rail",
    "Minecraft",
    "Monopoly GO!",
    "Infinity Nikki",
    "Snaky Cat",
    "PUBG Mobile",
    "Temple Run 2",
    "Wuthering Waves",
    "Tower of Fantasy",
    "The Room: Old Sins",
    "Vampire Survivors",
    "Titan Quest",
    "Star Wars: Knights of the Old Republic II",
    "Rome: Total War",
    "Among Us",
    "Clash Royale",
    "Asphalt 8",
    "Sniper 3D",

    # 21–40
    "BGMI (Battlegrounds Mobile India)",
    "Free Fire MAX",
    "Subway Surfers",
    "8 Ball Pool",
    "Clash of Clans",
    "Brawl Stars",
    "Apex Legends Mobile",
    "Real Racing 3",
    "Need for Speed: No Limits",
    "Mobile Legends: Bang Bang",
    "Shadow Fight 4: Arena",
    "Dead Cells",
    "Stumble Guys",
    "Candy Crush Saga",
    "Roblox",
    "Legends of Runeterra",
    "Dead by Daylight Mobile",
    "Modern Warships",
    "Terraria",
    "Hitman Sniper",

    # 41–60
    "Into the Dead 2",
    "Marvel Snap",
    "Alto’s Odyssey",
    "Alto’s Adventure",
    "Plants vs Zombies 2",
    "Mini Militia - Doodle Army 2",
    "Stick War: Legacy",
    "Real Cricket 24",
    "eFootball 2025",
    "Mortal Kombat Mobile",
    "Injustice 2",
    "Garena Undawn",
    "Warframe Mobile",
    "The Sims Mobile",
    "Goat Simulator 3",
    "Hill Climb Racing 2",
    "Crash Bandicoot: On the Run",
    "Angry Birds 2",
    "Soul Knight",
    "Jetpack Joyride 2",

    # 61–80
    "Grimvalor",
    "Black Desert Mobile",
    "Sky: Children of the Light",
    "ARK: Survival Evolved",
    "Star Wars: Galaxy of Heroes",
    "Among Trees Mobile",
    "Rebel Racing",
    "Vector 2",
    "Cover Fire",
    "Dead Trigger 2",
    "Hitman GO",
    "LIMBO",
    "Inside",
    "Monument Valley 2",
    "Monument Valley",
    "Plague Inc.",
    "Farming Simulator 23",
    "SimCity BuildIt",
    "Pocket City 2",
    "The Walking Dead: Survivors",

    # 81–100
    "Last Day on Earth: Survival",
    "Zombie Frontier 4",
    "War Robots",
    "Sniper Fury",
    "World War Heroes",
    "Modern Combat 5",
    "Total War Battles: Kingdom",
    "Battle Bay",
    "Critical Ops",
    "Payback 2",
    "Nova Legacy",
    "Arena Breakout",
    "Slay the Spire",
    "My Friend Pedro: Ripe for Revenge",
    "Granny 3",
    "Five Nights at Freddy’s",
    "The Escapists 2",
    "Don’t Starve: Pocket Edition",
    "Cat Quest II",
    "Tiny Room Stories: Town Mystery"
]
