data = [
    {'name': 'Goku', 'power_level': 9999, 'description': 'Saiyan who keeps finding stronger opponents', 'origin': 'Dragon Ball Z'},
    {'name': 'Vegeta', 'power_level': 9700, 'description': 'Proud prince who yells a lot but trains harder', 'origin': 'Dragon Ball Z'},
    {'name': 'Saitama', 'power_level': 9999, 'description': 'Defeats anyone with a single punch', 'origin': 'One Punch Man'},
    {'name': 'Naruto Uzumaki', 'power_level': 9300, 'description': 'Ninja who never gives up and loves ramen', 'origin': 'Naruto'},
    {'name': 'Sasuke Uchiha', 'power_level': 9200, 'description': 'Cool guy with lightning and revenge issues', 'origin': 'Naruto'},
    {'name': 'Madara Uchiha', 'power_level': 9800, 'description': 'Ancient Uchiha who refuses to die quietly', 'origin': 'Naruto'},
    {'name': 'Itachi Uchiha', 'power_level': 8900, 'description': 'Silent genius with tragic vibes', 'origin': 'Naruto'},
    {'name': 'Luffy', 'power_level': 9400, 'description': 'Rubber pirate aiming to be the Pirate King', 'origin': 'One Piece'},
    {'name': 'Zoro', 'power_level': 8800, 'description': 'Swordsman who cant navigate but slices mountains', 'origin': 'One Piece'},
    {'name': 'Kaido', 'power_level': 9600, 'description': 'Beast pirate whos basically unkillable', 'origin': 'One Piece'},
    {'name': 'Ichigo Kurosaki', 'power_level': 9100, 'description': 'Soul Reaper with too many transformations', 'origin': 'Bleach'},
    {'name': 'Aizen Sosuke', 'power_level': 9500, 'description': 'Master manipulator with god complex', 'origin': 'Bleach'},
    {'name': 'Tanjiro Kamado', 'power_level': 7800, 'description': 'Kind-hearted demon slayer with a sharp nose', 'origin': 'Demon Slayer'},
    {'name': 'Nezuko Kamado', 'power_level': 7600, 'description': 'Cute demon sister with deadly kicks', 'origin': 'Demon Slayer'},
    {'name': 'Rengoku Kyojuro', 'power_level': 8300, 'description': 'Flame Hashira with burning passion', 'origin': 'Demon Slayer'},
    {'name': 'Gojo Satoru', 'power_level': 9700, 'description': 'Strongest Jujutsu sorcerer with style', 'origin': 'Jujutsu Kaisen'},
    {'name': 'Sukuna', 'power_level': 9500, 'description': 'King of Curses who enjoys chaos', 'origin': 'Jujutsu Kaisen'},
    {'name': 'Yuta Okkotsu', 'power_level': 8700, 'description': 'Cursed boy with a powerful ghost girlfriend', 'origin': 'Jujutsu Kaisen'},
    {'name': 'Deku (Izuku Midoriya)', 'power_level': 8500, 'description': 'Future symbol of peace with broken bones', 'origin': 'My Hero Academia'},
    {'name': 'Bakugo Katsuki', 'power_level': 8400, 'description': 'Explosive hero who screams motivation', 'origin': 'My Hero Academia'},
    {'name': 'All Might', 'power_level': 9300, 'description': 'Symbol of peace and perfect smile', 'origin': 'My Hero Academia'},
    {'name': 'Levi Ackerman', 'power_level': 8900, 'description': 'Humanitys strongest and cleanest soldier', 'origin': 'Attack on Titan'},
    {'name': 'Eren Yeager', 'power_level': 9400, 'description': 'Titan shifter with freedom issues', 'origin': 'Attack on Titan'},
    {'name': 'Mikasa Ackerman', 'power_level': 8600, 'description': 'Loyal warrior with deadly precision', 'origin': 'Attack on Titan'},
    {'name': 'Light Yagami', 'power_level': 8300, 'description': 'Smart guy who thinks hes a god', 'origin': 'Death Note'},
    {'name': 'L Lawliet', 'power_level': 8100, 'description': 'Detective who fights evil with coffee and brains', 'origin': 'Death Note'},
    {'name': 'Gon Freecss', 'power_level': 8500, 'description': 'Optimistic hunter who punches first, asks later', 'origin': 'Hunter x Hunter'},
    {'name': 'Killua Zoldyck', 'power_level': 8400, 'description': 'Assassin boy with lightning speed', 'origin': 'Hunter x Hunter'},
    {'name': 'Hisoka', 'power_level': 8700, 'description': 'Magician who finds fights... too exciting', 'origin': 'Hunter x Hunter'},
    {'name': 'Edward Elric', 'power_level': 8300, 'description': 'Alchemist with short temper and metal arm', 'origin': 'Fullmetal Alchemist'},
    {'name': 'Alphonse Elric', 'power_level': 8100, 'description': 'Gentle soul in a giant armor body', 'origin': 'Fullmetal Alchemist'},
    {'name': 'Meliodas', 'power_level': 9500, 'description': 'Cheerful demon prince who loves ale', 'origin': 'Seven Deadly Sins'},
    {'name': 'Escanor', 'power_level': 9800, 'description': 'The One who is strongest under the sun', 'origin': 'Seven Deadly Sins'},
    {'name': 'Natsu Dragneel', 'power_level': 8900, 'description': 'Fire dragon slayer who yells about friendship', 'origin': 'Fairy Tail'},
    {'name': 'Erza Scarlet', 'power_level': 8600, 'description': 'Armored queen who can change outfits instantly', 'origin': 'Fairy Tail'},
    {'name': 'Gintoki Sakata', 'power_level': 8500, 'description': 'Lazy samurai with silver hair and sarcasm', 'origin': 'Gintama'},
    {'name': 'Mob (Shigeo Kageyama)', 'power_level': 9200, 'description': 'Emotionally unstable psychic with massive power', 'origin': 'Mob Psycho 100'},
    {'name': 'Shinra Kusakabe', 'power_level': 8400, 'description': 'Fire soldier who literally runs on flames', 'origin': 'Fire Force'},
    {'name': 'Asta', 'power_level': 8800, 'description': 'Magicless knight with anti-magic muscles', 'origin': 'Black Clover'},
    {'name': 'Yami Sukehiro', 'power_level': 9100, 'description': 'Captain who fights with dimension cuts', 'origin': 'Black Clover'},
    {'name': 'Roronoa Zoro', 'power_level': 8800, 'description': 'Three-sword samurai who always gets lost', 'origin': 'One Piece'},
    {'name': 'Sanji', 'power_level': 8600, 'description': 'Chef who kicks harder than he cooks', 'origin': 'One Piece'},
    {'name': 'Nico Robin', 'power_level': 8200, 'description': 'Archaeologist with extra hands and deep trauma', 'origin': 'One Piece'},
    {'name': 'Brook', 'power_level': 8100, 'description': 'Skeleton musician who loves bad jokes', 'origin': 'One Piece'},
    {'name': 'Franky', 'power_level': 8300, 'description': 'Cyborg who shouts SUPER and builds ships', 'origin': 'One Piece'},
    {'name': 'Shanks', 'power_level': 9700, 'description': 'Chill emperor who ends wars with words', 'origin': 'One Piece'},
    {'name': 'Whitebeard', 'power_level': 9800, 'description': 'World’s strongest man and father figure', 'origin': 'One Piece'},
    {'name': 'Boa Hancock', 'power_level': 8700, 'description': 'Pirate empress with beauty and pride', 'origin': 'One Piece'},
    {'name': 'Trafalgar Law', 'power_level': 8900, 'description': 'Doctor pirate who can slice reality', 'origin': 'One Piece'},
    {'name': 'Buggy the Clown', 'power_level': 7200, 'description': 'Comedic pirate who somehow became a warlord', 'origin': 'One Piece'},
    {'name': 'Gon Freecss', 'power_level': 8500, 'description': 'Optimistic hunter who never gives up', 'origin': 'Hunter x Hunter'},
    {'name': 'Kurapika', 'power_level': 8700, 'description': 'Chains of vengeance powered by rage', 'origin': 'Hunter x Hunter'},
    {'name': 'Meruem', 'power_level': 9800, 'description': 'Ant king who became too human', 'origin': 'Hunter x Hunter'},
    {'name': 'Netero', 'power_level': 9500, 'description': 'Old man who can punch faster than light', 'origin': 'Hunter x Hunter'},
    {'name': 'Giorno Giovanna', 'power_level': 9000, 'description': 'Gangstar with a golden dream', 'origin': 'JoJo’s Bizarre Adventure'},
    {'name': 'Jotaro Kujo', 'power_level': 9400, 'description': 'Cool delinquent who stops time', 'origin': 'JoJo’s Bizarre Adventure'},
    {'name': 'Dio Brando', 'power_level': 9600, 'description': 'Immortal vampire with fabulous poses', 'origin': 'JoJo’s Bizarre Adventure'},
    {'name': 'Joseph Joestar', 'power_level': 8800, 'description': 'Smart trickster who shouts “OH NOOOO!”', 'origin': 'JoJo’s Bizarre Adventure'},
    {'name': 'Kira Yoshikage', 'power_level': 8500, 'description': 'Serial killer who just wants a quiet life', 'origin': 'JoJo’s Bizarre Adventure'},
    {'name': 'Giorno’s Gold Experience Requiem', 'power_level': 9998, 'description': 'Literally rewrites fate itself', 'origin': 'JoJo’s Bizarre Adventure'},
    {'name': 'Light Yagami', 'power_level': 8300, 'description': 'Student with a god complex and notebook', 'origin': 'Death Note'},
    {'name': 'Ryuk', 'power_level': 9100, 'description': 'Shinigami who loves apples and chaos', 'origin': 'Death Note'},
    {'name': 'Edward Elric', 'power_level': 8300, 'description': 'Short but mighty alchemist', 'origin': 'Fullmetal Alchemist'},
    {'name': 'Roy Mustang', 'power_level': 8700, 'description': 'Flame alchemist who snaps for drama', 'origin': 'Fullmetal Alchemist'},
    {'name': 'Scar', 'power_level': 8800, 'description': 'Avenger with deadly tattoos', 'origin': 'Fullmetal Alchemist'},
    {'name': 'Inuyasha', 'power_level': 8600, 'description': 'Half-demon with a big sword and bigger temper', 'origin': 'Inuyasha'},
    {'name': 'Sesshomaru', 'power_level': 9400, 'description': 'Calm demon prince with icy beauty', 'origin': 'Inuyasha'},
    {'name': 'Kagome Higurashi', 'power_level': 7400, 'description': 'Schoolgirl who travels through time', 'origin': 'Inuyasha'},
    {'name': 'Yusuke Urameshi', 'power_level': 8800, 'description': 'Spirit detective with fists of fire', 'origin': 'Yu Yu Hakusho'},
    {'name': 'Hiei', 'power_level': 9000, 'description': 'Edgy demon with dragon powers', 'origin': 'Yu Yu Hakusho'},
    {'name': 'Kurama', 'power_level': 8800, 'description': 'Elegant demon fox with a garden of death', 'origin': 'Yu Yu Hakusho'},
    {'name': 'Gintoki Sakata', 'power_level': 8500, 'description': 'Lazy samurai who still wins somehow', 'origin': 'Gintama'},
    {'name': 'Kagura', 'power_level': 8200, 'description': 'Alien girl who eats too much and hits harder', 'origin': 'Gintama'},
    {'name': 'Hijikata Toshiro', 'power_level': 8300, 'description': 'Serious cop addicted to mayonnaise', 'origin': 'Gintama'},
    {'name': 'Shinobu Kocho', 'power_level': 7800, 'description': 'Smiling insect Hashira with deadly poison', 'origin': 'Demon Slayer'},
    {'name': 'Muzan Kibutsuji', 'power_level': 9700, 'description': 'Demon king with serious Michael Jackson vibes', 'origin': 'Demon Slayer'},
    {'name': 'Kanao Tsuyuri', 'power_level': 7600, 'description': 'Quiet demon slayer with perfect reflexes', 'origin': 'Demon Slayer'},
    {'name': 'Killua Zoldyck', 'power_level': 8400, 'description': 'Assassin kid with lightning reflexes', 'origin': 'Hunter x Hunter'},
    {'name': 'Leorio', 'power_level': 7500, 'description': 'Future doctor and wannabe rich man', 'origin': 'Hunter x Hunter'},
    {'name': 'Kenshin Himura', 'power_level': 8700, 'description': 'Legendary samurai who swore never to kill', 'origin': 'Rurouni Kenshin'},
    {'name': 'Sanosuke Sagara', 'power_level': 8100, 'description': 'Street fighter with a huge sword and bigger heart', 'origin': 'Rurouni Kenshin'},
    {'name': 'Shishio Makoto', 'power_level': 9200, 'description': 'Burned villain wrapped in bandages', 'origin': 'Rurouni Kenshin'},
    {'name': 'Spike Spiegel', 'power_level': 8500, 'description': 'Cool bounty hunter who lives for jazz', 'origin': 'Cowboy Bebop'},
    {'name': 'Faye Valentine', 'power_level': 8100, 'description': 'Con artist with charm and debt', 'origin': 'Cowboy Bebop'},
    {'name': 'Vicious', 'power_level': 8800, 'description': 'Cold-hearted swordsman from Red Dragon syndicate', 'origin': 'Cowboy Bebop'},
    {'name': 'Edward Wong', 'power_level': 7800, 'description': 'Hyper hacker child genius', 'origin': 'Cowboy Bebop'},
    {'name': 'Alucard', 'power_level': 9700, 'description': 'Immortal vampire who laughs in bullets', 'origin': 'Hellsing'},
    {'name': 'Seras Victoria', 'power_level': 8400, 'description': 'Vampire cop with a massive gun', 'origin': 'Hellsing'},
    {'name': 'Integra Hellsing', 'power_level': 8200, 'description': 'Cool boss lady commanding monsters', 'origin': 'Hellsing'}
  ]
